services:
  node-dev-env:
    build: .
    command: npm run dev
    ports: 
      - 5173:5173
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    working_dir: /app
    container_name: frontend

volumes:
  node_modules:
